[package]
name = "stick_rc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2="0.35.2"
paho-mqtt="0.11.1"
serde_yaml="0.8.24"
serde={version="1.0.136", features=["derive"]}
